% all mr algo
ebr=1; rc=2; hp=3; dw=4;
gcs = [ebr rc hp dw];
threads = [2];
elements = [100];
update = [20];
db_prg_total_avg = 0;
db_prg_total_std = 0;
for gc = gcs
    for t = threads
        for e = elements
            for u = update
                ans = sscanf(fgetl(0), "%u")';
                db_prg_total_avg(...
                    find(gcs == gc), ...
                    find(threads == t), ...
                    find(elements == e), ...
                    find(update == u) ...
                    ) = ans(1);
                db_prg_total_std(...
                    find(gcs == gc), ...
                    find(threads == t), ...
                    find(elements == e), ...
                    find(update == u) ...
                    ) = ans(2);
            endfor
        endfor
    endfor
endfor

db_prg_footprint_avg = 0;
db_prg_footprint_std = 0;
for gc = gcs
    for t = threads
        for e = elements
            for u = update
                ans = sscanf(fgetl(0), "%u")';
                db_prg_footprint_avg(...
                    find(gcs == gc), ...
                    find(threads == t), ...
                    find(elements == e), ...
                    find(update == u) ...
                    ) = ans(1);
                db_prg_footprint_std(...
                    find(gcs == gc), ...
                    find(threads == t), ...
                    find(elements == e), ...
                    find(update == u) ...
                    ) = ans(2);
            endfor
        endfor
    endfor
endfor
 db_prg_total_avg
 db_prg_total_std
 db_prg_footprint_avg
 db_prg_footprint_std
save db_prg.mat db_prg_total_avg db_prg_total_std db_prg_footprint_avg db_prg_footprint_std
